import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Pokemon from "@/Components/Pokemon";
import PokemonDescription from "@/Components/PokemonDescription";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className={`w-full py-6 min-h-screen ${styles.pokemonContainer}`}>
          <div className="logo flex justify-center  py-10">
            <Image
              src={"/Media Asset/Logo.png"}
              width={200}
              height={100}
              alt="pokemon-logo"
            />
          </div>
          <div className="grid grid-cols-5 gap-10  max-w-7xl my-0 mx-auto">
            <Pokemon />
            <Pokemon />
            <Pokemon />
            <Pokemon />
            <Pokemon />
            <Pokemon />
            <Pokemon />
          </div>
        </div>
        <PokemonDescription />
      </main>
    </>
  );
}
